### ISSUE TITLE
Mirror hapi reply behavior for hydrate callback

### ISSUE THREAD

**Issue by mshick** [continuationlabs/tacky#16]
I think it would be useful if the signature of the hydrate callback worked similar to the hapi `reply` callback. I believe it would be more consistent in the hapi eco-system, especially if you are upgraded a standard reply handler to be a tacky hydrate function.

That is to say, rather than `callback(err, res)` if you tested the first arg to see if it is an error object, rather than just treating it as an error.

I think there are a few other smarts in the hapi `reply`, promises, and so forth, and closest parity to those would be great (maybe there's even an internal function that can be tapped into?).

This is all personal preference -- very useful plugin regardless. Thanks!

**Comment by arb** [comment]
I did think about this, but the hydrate function technically isn't replying back to the requestor, it is only hydrating the cache. For that reason, I used the Node standard `err, data` callback style to keep it simple and consistent the rest of Node. 

Glad you find the plugin useful.

**Comment by mshick** [comment]
Cool, thanks for explaining. Makes sense.
